version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "chore"
    include: "scope"
  ignore:
    - dependency-name: "alembic"
      versions: ["1.7.3"]
  open-pull-requests-limit: 10
