"""init

Revision ID: 00e4f3fe968e
Revises: 
Create Date: 2021-10-13 22:06:41.180957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00e4f3fe968e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=30), nullable=False),
        sa.Column("last_name", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=100), nullable=True),
        sa.Column("chinese_name", sa.String(length=255), nullable=True),
        sa.Column("nickname", sa.String(length=255), nullable=True),
        sa.Column("phone_number", sa.String(length=30), nullable=True),
        sa.Column("shirt_size", sa.String(length=10), nullable=True),
        sa.Column("company", sa.String(length=50), nullable=True),
        sa.Column("school", sa.String(length=50), nullable=True),
        sa.Column(
            "register_date", sa.Date(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("dietary_restriction", sa.String(length=255), nullable=True),
        sa.Column("reimbursement_platform", sa.String(length=50), nullable=True),
        sa.Column("reimbursement_method", sa.String(length=50), nullable=True),
        sa.Column("reimbursement_phone_number", sa.String(length=30), nullable=True),
        sa.Column("reimbursement_email", sa.String(length=255), nullable=True),
        sa.Column("join_date", sa.Date(), nullable=True),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("memo", sa.JSON(), nullable=True),
        sa.Column("type", sa.String(length=30), nullable=True),
        sa.Column("review_by_id", sa.String(length=100), nullable=True),
        sa.Column("review_status", sa.String(length=30), nullable=True),
        sa.Column("has_iam_google_account", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["review_by_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("email"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_account_email"), "account", ["email"], unique=False)
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("session", sa.Integer(), nullable=True),
        sa.Column("chinese_name", sa.String(length=255), nullable=True),
        sa.Column("english_name", sa.String(length=60), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("memo", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_email"), "group", ["email"], unique=True)
    op.create_table(
        "accout_group",
        sa.Column("account_id", sa.String(length=100), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("account_id", "group_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accout_group")
    op.drop_index(op.f("ix_group_email"), table_name="group")
    op.drop_table("group")
    op.drop_index(op.f("ix_account_email"), table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###
