"""user_init

Revision ID: 3f5ad8caef2b
Revises: 00e4f3fe968e
Create Date: 2021-10-16 21:31:27.045109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f5ad8caef2b"
down_revision = "00e4f3fe968e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_token",
        sa.Column("account_id", sa.String(length=100), nullable=False),
        sa.Column("token", sa.String(length=300), nullable=True),
        sa.Column("expire_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_table(
        "oauth",
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("token", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("provider_user_id", sa.String(length=256), nullable=False),
        sa.Column("account_id", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint("provider_user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth")
    op.drop_table("account_token")
    # ### end Alembic commands ###
